import type { Category } from "./CategoryList";

export const CATEGORY_DATA: Category[] = [
  {
    id: "cuisine",
    label: "Cuisine",
    items: [
      { id: "italian", label: "Italian" },
      { id: "korean", label: "Korean" },
      { id: "mexican", label: "Mexican" },
      { id: "french", label: "French" },
      { id: "chinese", label: "Chinese" },
      { id: "american", label: "American" },
      { id: "indian", label: "Indian" },
      { id: "mediterranean", label: "Mediterranean" },
      { id: "thai", label: "Thai" },
      { id: "greek", label: "Greek" },
      { id: "vietnamese", label: "Vietnamese" },
      { id: "spanish", label: "Spanish" },
      { id: "japanese", label: "Japanese" },
      { id: "german", label: "German" },
    ],
  },
  {
    id: "mealType",
    label: "Meal Type",
    items: [
      { id: "breakfast", label: "Breakfast" },
      { id: "brunch", label: "Brunch" },
      { id: "lunch", label: "Lunch" },
      { id: "dinner", label: "Dinner" },
      { id: "dessert", label: "Dessert" },
      { id: "snack", label: "Snack" },
      { id: "appetizer", label: "Appetizer" },
      { id: "beverage", label: "Beverage" },
    ],
  },
  {
    id: "dietary",
    label: "Dietary",
    items: [
      { id: "low-carb", label: "Low-Carb" },
      { id: "keto", label: "Keto" },
      { id: "gluten-free", label: "Gluten-Free" },
      { id: "dairy-free", label: "Dairy-Free" },
      { id: "high-protein", label: "High-Protein" },
      { id: "paleo", label: "Paleo" },
      { id: "vegetarian", label: "Vegetarian" },
      { id: "nut-free", label: "Nut-Free" },
      { id: "low-sodium", label: "Low-Sodium" },
    ],
  },
  {
    id: "method",
    label: "Method",
    items: [
      { id: "baking", label: "Baking" },
      { id: "grilling", label: "Grilling" },
      { id: "frying", label: "Frying" },
      { id: "boiling", label: "Boiling" },
      { id: "steaming", label: "Steaming" },
      { id: "sauteing", label: "Sautéing" },
      { id: "roasting", label: "Roasting" },
      { id: "slow-cooking", label: "Slow Cooking" },
      { id: "pressure-cooking", label: "Pressure Cooking" },
      { id: "raw", label: "Raw" },
    ],
  },
  {
    id: "main",
    label: "Main Ingredient",
    items: [
      { id: "chicken", label: "Chicken" },
      { id: "beef", label: "Beef" },
      { id: "pork", label: "Pork" },
      { id: "fish", label: "Fish" },
      { id: "beans", label: "Beans" },
      { id: "vegetables", label: "Vegetables" },
      { id: "cheese", label: "Cheese" },
      { id: "seafood", label: "Seafood" },
      { id: "eggs", label: "Eggs" },
      { id: "tofu", label: "Tofu" },
      { id: "rice", label: "Rice" },
      { id: "pasta", label: "Pasta" },
      { id: "fruits", label: "Fruits" },
      { id: "nuts", label: "Nuts" },
    ],
  },
];
