import type { RecipeItemProps } from './RecipeItem';

export const sampleRecipes: RecipeItemProps[] = [
	{
		id: '1',
		title: 'Egg Fried Rice',
		creator: 'Amanda Suarez',
		totalTime: '15 mins',
		rating: 4.8,
		reviewCount: 18,
		imageUrl: '/delicious-egg-fried-rice-in-a-pan.jpg',
		isSaved: false,
	},
	{
		id: '2',
		title: 'Instant Pot Mac & Cheese',
		creator: 'Ella Quittner',
		totalTime: '20 mins',
		rating: 4.7,
		reviewCount: 29,
		imageUrl: '/creamy-mac-and-cheese-in-instant-pot.jpg',
		isSaved: true,
	},
	{
		id: '3',
		title: 'French Bread Pepperoni Pizza',
		creator: 'Milton Clark',
		totalTime: '25 mins',
		rating: 4.9,
		reviewCount: 11,
		imageUrl: '/french-bread-pepperoni-pizza-on-baking-sheet.jpg',
		isSaved: false,
	},
	{
		id: '4',
		title: 'Healthy Rice Cooker Garlic Shrimp with Chorizo',
		creator: 'Emily Weinberger',
		totalTime: '40 mins',
		rating: 4.6,
		reviewCount: 33,
		imageUrl: '/garlic-shrimp-with-chorizo-in-rice-cooker.jpg',
		isSaved: false,
	},
	{
		id: '5',
		title: 'Classic Beef Tacos',
		creator: 'Maria Rodriguez',
		totalTime: '30 mins',
		rating: 4.8,
		reviewCount: 45,
		imageUrl: '/classic-beef-tacos-with-fresh-toppings.jpg',
		isSaved: true,
	},
	{
		id: '6',
		title: 'Chicken Alfredo Pasta',
		creator: 'Tony Italiano',
		totalTime: '35 mins',
		rating: 4.7,
		reviewCount: 22,
		imageUrl: '/creamy-chicken-alfredo.png',
		isSaved: false,
	},
];
